// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Xamarin.InAppPurchase;

namespace InAppPurchaseTest
{
    public partial class PurchaseTableViewController : UITableViewController
    {
        #region Computed Properties
        /// <summary>
        /// Gets the data source.
        /// </summary>
        /// <value>The data source.</value>
        public PurchaseTableSource DataSource
        {
            get { return (PurchaseTableSource)TableView.Source; }
        }
        #endregion

        #region Constructors
        /// <summary>
        /// Initializes a new instance of the <see cref="InAppPurchaseTest.PurchaseTableViewController"/> class.
        /// </summary>
        /// <param name="handle">Handle.</param>
        public PurchaseTableViewController(IntPtr handle) : base(handle)
        {
        }
        #endregion

        #region Public Override Methods
        /// <summary>
        /// Views the did load.
        /// </summary>
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            // Adjust for iOS 7
            TableView.ContentInset = new UIEdgeInsets(20, 0, 0, 0);
            TableView.ContentOffset = new System.Drawing.PointF(0, -20);

            // Register the TableView's data source
            TableView.Source = new PurchaseTableSource(this);
            Extensions.InAppPurchaseHandler.PurchasedProducts
                      .Subscribe((InAppProduct[] obj) =>
                      {
                          DataSource.LoadData(obj);
                          TableView.ReloadData();
                          if (obj.Length == 0)
                          {
                              PurchasesTab.BadgeValue = null;
                          }
                          else
                          {
                              PurchasesTab.BadgeValue = obj.Length.ToString();
                          }
                      });
        }
        #endregion


    }
}
